package ;

@:native ("Graphics")
extern class Graphics {

	private var _active:Bool;
	private var _activeInstructions:Array[Command];
	private var _dirty:Bool;
	private var _fillInstructions:Array[Command];
	private var _instructions:Array[Command];
	private var _oldInstructions:Array[Command];
	private var _strokeInstructions:Array[Command];
	private var _strokeStyleInstructions:Array[Command];
	private var a:Void;
	private var at:Void;
	private var bf:Void;
	private var bs:Void;
	private var bt:Void;
	private var c:Void;
	private var cp:Void;
	private var dc:Void;
	private var de:Void;
	private var dp:Void;
	private var dr:Void;
	private var ef:Void;
	private var es:Void;
	private var f:Void;
	private var lf:Void;
	private var ls:Void;
	private var lt:Void;
	private var mt:Void;
	private var p:Void;
	private var qt:Void;
	private var r:Void;
	private var rc:Void;
	private var rf:Void;
	private var rr:Void;
	private var rs:Void;
	private var s:Void;
	private var ss:Void;
	public static var _ctx:CanvasRenderingContext2D;
	public static var BASE_64:Dynamic;
	public static var beginCmd:Command;
	public static var fillCmd:Command;
	public static var STROKE_CAPS_MAP:Array[String];
	public static var STROKE_JOINTS_MAP:Array[String];
	public static var strokeCmd:Command;
	public var curveTo:Dynamic;
	public var drawRect:Dynamic;

	private function _newPath ():Dynamic;
	private function _setProp (name:String, value:String):Dynamic;
	private function _updateInstructions ():Dynamic;
	private function initialize (instructions:String):Dynamic;
	public function arc (x:Float, y:Float, radius:Float, startAngle:Float, endAngle:Float, anticlockwise:Bool):Graphics;
	public function arcTo (x1:Float, y1:Float, x2:Float, y2:Float, radius:Float):Graphics;
	public function beginBitmapFill (image:Void, repetition:String):Graphics;
	public function beginBitmapStroke (image:Dynamic, repetition:String):Graphics;
	public function beginFill (color:String):Graphics;
	public function beginLinearGradientFill (colors:Array[String], ratios:Array[Number], x0:Float, y0:Float, x1:Float, y1:Float):Graphics;
	public function beginLinearGradientStroke (colors:Void, ratios:Void, x0:Void, y0:Void, x1:Void, y1:Void):Graphics;
	public function beginRadialGradientFill (colors:Array[String], ratios:Array[Number], x0:Float, y0:Float, r0:Float, x1:Float, y1:Float, r1:Float):Graphics;
	public function beginRadialGradientStroke (colors:Void, ratios:Void, x0:Void, y0:Void, r0:Void, x1:Void, y1:Void, r1:Void):Graphics;
	public function beginStroke (color:Void):Graphics;
	public function clear ():Graphics;
	public function clone ():Graphics;
	public function closePath ():Graphics;
	public function decodePath (str:String):Graphics;
	public function draw (ctx:CanvasRenderingContext2D):Dynamic;
	public function drawAsPath (ctx:CanvasRenderingContext2D):Dynamic;
	public function drawCircle (x:Float, y:Float, radius:Float):Graphics;
	public function drawEllipse (x:Float, y:Float, w:Float, h:Float):Graphics;
	public function drawPolyStar (x:Float, y:Float, radius:Float, sides:Float, pointSize:Float, angle:Float):Graphics;
	public function drawRoundRect (x:Float, y:Float, w:Float, h:Float, radius:Float):Graphics;
	public function drawRoundRectComplex (x:Float, y:Float, w:Float, h:Float, radiusTL:Float, radiusTR:Float, radiusBR:Float, radiusBL:Float):Graphics;
	public function endStroke ():Graphics;
	public function exec (scope:Dynamic):Dynamic;
	public function lineTo (x:Float, y:Float):Graphics;
	public function moveTo (x:Float, y:Float):Graphics;
	public function quadraticCurveTo (cpx:Float, cpy:Float, x:Float, y:Float):Graphics;
	public function rect (x:Float, y:Float, w:Float, h:Float):Graphics;
	public function setStrokeStyle (thickness:Void, caps:Void, joints:Void, miter:Void):Graphics;
	public function toString ():String;
	public static function getHSL (hue:Float, saturation:Float, lightness:Float, alpha:Float):Void;
	public static function getRGB (r:Float, g:Float, b:Float, alpha:Float):Void;

}